CREATE TABLE "NODE_LOGGER"
(    "ID" NUMBER,
     "LAST_ACTIVE_ON" TIMESTAMP (6),
     "SERVICE_CODE" VARCHAR2(255 BYTE)
);
ALTER TABLE "INVOICEQ_ADAPTER"."NODE_LOGGER" ADD PRIMARY KEY ("ID");

CREATE SEQUENCE node_sequence;

CREATE SEQUENCE attachment_Seq;