create or replace PROCEDURE XXSAPTCO_CALL_ZATCA_AFTER(P_CUSTOMER_TRX_ID NUMBER ,P_STATUS VARCHAR2 , P_RESPONSE CLOB) AS
v_resp  VARCHAR2(150);
v_seq   NUMBER;
errbuf  VARCHAR2(200);
retcode NUMBER;
BEGIN

---UPDATE STATUS AND RESPONSE THAT RETERIVE FROM ZATCA IN AR_CUSTOMER_TRX_ALL

select max(seq_id)
into   v_seq
from   XXSAPTCO_ZATCA_HEADER_ERP
where  customer_trx_id = P_CUSTOMER_TRX_ID;

IF P_RESPONSE IS NOT NULL AND P_STATUS IN ('BUSINESS_FAILED','TECHNICAL_FAILED') THEN
v_resp := substr(P_RESPONSE,1,150);
END IF;

APPS.XXSAPTCO_ZATCA_PKG.XXSAPTCO_INVOICE_ZATCA_STATUS(P_CUSTOMER_TRX_ID,P_STATUS,v_resp);

---Make Invoice Not Complete if we have error retrieve from ZATCA
IF P_STATUS = 'SUCCESS' THEN/*IN ('BUSINESS_FAILED','TECHNICAL_FAILED') THEN */
APPS.XXSAPTCO_ZATCA_PKG.XXSAPTCO_INVOICE_COMPLETE(P_CUSTOMER_TRX_ID);

/*ELSE*/
begin
APPS.XXSAPTCO_ZATCA_PKG.XXSAPTCO_INVOICE_ATTACHMENT(errbuf,retcode);
--APPS.XXSAPTCO_ZATCA_PKG.XXSAPTCO_INVOICE_COMPLETE(P_CUSTOMER_TRX_ID);
end;
END IF;

COMMIT;
END;